/**
 * Like uniqBy, but instead of producing a subset of the original collection,
 * it produces a list of values generated by the iterFn.
 * @template T
 * @param {(t: T) => number|string|boolean|null|undefined} iterFn 
 * @returns {(prev: (number|string|boolean|null|undefined)[], curr: T) => (number|string|boolean|null|undefined)[]}
 */
export function uniqValuesByRdc(iterFn) {

  return (prev, curr) => {
    const currentIterValue = iterFn(curr)
    if (!prev.some(item => item === currentIterValue)) {
      prev.push(currentIterValue)
    }
    return prev
    
  }
}